apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          # Use the image with Cloud Build tag
          image: asia-south1-docker.pkg.dev/gcp-cicd-pipeline-demo-project/webapp-repo/my-app:IMAGE_TAG
          imagePullPolicy: Always
          #TAG
          ports:
            - containerPort: 80
      # Optional: ensures GKE uses default service account for image pull
      #imagePullSecrets:
        #- name: gcp-artifact-registry