apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          # Use the image with Cloud Build tag
          image: asia-south1-docker.pkg.dev/${_PROJECT_ID}/webapp-repo/my-app
          imagePullPolicy: Always
          #TAG
          ports:
            - containerPort: 80
      # Optional: ensures GKE uses default service account for image pull
      #imagePullSecrets:
        #- name: gcp-artifact-registry